CREATE TABLE [dbo].[ESTUDIANTES](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [varchar](150) NOT NULL,
	[EDAD] [int] NULL,
	[DOCUMENTO] [bigint] NULL,
	[TIPO_LICENCIA] [varchar](50) NULL
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[ESTUDIANTES] ON 
GO
INSERT [dbo].[ESTUDIANTES] ([ID], [NOMBRE], [EDAD], [DOCUMENTO], [TIPO_LICENCIA]) VALUES (1, N'Juan Jaminton yate', 30, 987654321, N'C1')
GO
INSERT [dbo].[ESTUDIANTES] ([ID], [NOMBRE], [EDAD], [DOCUMENTO], [TIPO_LICENCIA]) VALUES (2, N'Pepito Perez Fernandez', 17, 23456787654, N'B3')
GO
INSERT [dbo].[ESTUDIANTES] ([ID], [NOMBRE], [EDAD], [DOCUMENTO], [TIPO_LICENCIA]) VALUES (3, N'Elizabeth Gerrero H', 22, 7654323456, N'C1')
GO
INSERT [dbo].[ESTUDIANTES] ([ID], [NOMBRE], [EDAD], [DOCUMENTO], [TIPO_LICENCIA]) VALUES (4, N'Nicola Tesla', 44, 8765432345, N'A1')
GO
SET IDENTITY_INSERT [dbo].[ESTUDIANTES] OFF
GO